# ========== Profile ========== #
# avatar
avatar: /avatar/avatar.jpg
# author name
author: visionNoob
# signature
signature: Jaewon Lee
# SNS (you can custom the order)
social:
  email: insurgen92@gmail.com
  github: //github.com/visionNoob
  # wechat and qq should be a path of qr-code image
  wechat: #/assets/example_qr.png
  qq: 
  telegram: 
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  segmentFault: 
  juejin: 
  v2ex: 
  bilibili: 
  linkedin: 
  steam: 
  others: 
  rss: 
# friends
#friends:
#  friendA: //www.baidu.com
#  friendB: //www.google.com
#  friendC: 
about:
  enable: true
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site (good for SEO)
SEO_title: visionNoob's Studio
# keywords for site (good for SEO)
SEO_keywords:
  - visionNoob
  - 'hexo-theme'
  - 'hexo-blog'
# main title shown in header image
main_title: visionNoob's Studio.
# subtitle
subtitle: Computer Vision Playground :D
# site haeder image
site_header_image: 'https://user-images.githubusercontent.com/15168540/66091512-05c9b780-e5c3-11e9-9456-9c57caefc023.png'
# post haeder image
post_header_image: 'https://user-images.githubusercontent.com/15168540/66091512-05c9b780-e5c3-11e9-9456-9c57caefc023.png'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Search ========== #
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We did not find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: visionnoob
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: 
  valine_appKey: 
  valine_placeHolder: 

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 144555394
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50

#language
language: en

# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">This document is licensed under a Creative Commons Attribution-Noncommercial 4.0 International License Agreement.'